module.exports = {
  CREATE_APPLICATION_FAILURE: { code: 400, type: 'GENERAL_ERROR', message: 'CREATE_APPLICATION_FAILURE' },
  FETCH_APPLICATION_FAILURE: { code: 400, type: 'GENERAL_ERROR', message: 'FETCH_APPLICATION_FAILURE' },
  UPDATE_APPLICATION_FAILURE: { code: 400, type: 'GENERAL_ERROR', message: 'UPDATE_APPLICATION_FAILURE' }
}
